### ISSUE TITLE
FileNotFoundError while `python -m irust_kernel.install`

### ISSUE THREAD

**Issue by eatPizza311** [sigmaSd/IRust#123]
When following the [install instruction](https://github.com/sigmaSd/IRust/blob/master/crates/irust_repl/README.md#installationl) for Jupyter kernel, if I execute `python -m irust_kernel.install` there will be the following error:
```
Traceback (most recent call last):
  File "/Users/me/miniforge3/envs/rust/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/me/miniforge3/envs/rust/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/me/miniforge3/envs/rust/lib/python3.10/site-packages/irust_kernel/install.py", line 109, in <module>
    main()
  File "/Users/me/miniforge3/envs/rust/lib/python3.10/site-packages/irust_kernel/install.py", line 106, in main
    install_my_kernel_spec(user=user, prefix=prefix, local_build=args.local_build)
  File "/Users/me/miniforge3/envs/rust/lib/python3.10/site-packages/irust_kernel/install.py", line 53, in install_my_kernel_spec
    shutil.copy2(src, dst)
  File "/Users/me/miniforge3/envs/rust/lib/python3.10/shutil.py", line 434, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/Users/me/miniforge3/envs/rust/lib/python3.10/shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'target/release/examples/re'
```

**Comment by sigmaSd** [comment]
fixed by https://github.com/sigmaSd/IRust/pull/124
